services:
  ecommerce.api:
    image: ecommerce.api
    build:
      context: .
      dockerfile: Ecommerce.Api/Dockerfile

  testdemoinfra:
    image: testdemoinfra
    build:
      context: .
      dockerfile: TestDemoInfra/Dockerfile

